apiVersion: apps/v1
kind: Deployment
metadata:
  name: convert-secret
spec:
  template:
    spec:
      serviceAccountName: convert-secret
      terminationGracePeriodSeconds: 10
      volumes:
        - name: convert-secret
          configMap:
            name: convert-secret
      containers:
        - name: convert-secret
          volumeMounts:
            - name: convert-secret
              mountPath: /scripts
          image: image-registry.openshift-image-registry.svc:5000/openshift/tools:latest
          command:
            - bash
            - /scripts/convert-secret.sh
          env:
            - name: CONVERT_SECRET_NAME
              value: bucketclaim-example-bucket
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
