apiVersion: v1
kind: Secret
metadata:
  name: bucketclaim-example-bucket
stringData:
  BucketInfo: >-
    {
      "metadata": {
        "name": "bc-f87a4cc9-a344-47d2-8181-1793f8dcc6a1",
        "creationTimestamp": null
      },
      "spec": {
        "bucketName": "fb-bucketbd9d1050-bda8-437f-996b-dde341f5fb72",
        "authenticationType": "KEY",
        "secretS3": {
          "endpoint": "s3.infra.oac.ocp.massopen.cloud",
          "region": "",
          "accessKeyID": "ACCESSKEY",
          "accessSecretKey": "SECRETKEY"
        },
        "secretAzure": null,
        "protocols": [
          ""
        ]
      }
    }
