apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lars-sandbox

labels:
  - pairs:
      app: convert-secret
    includeSelectors: true

resources:
  - rbac.yaml
  - secretstore.yaml
  - bucketclaim-example-bucket-converted.yaml

replacements:
  - source:
      kind: SecretStore
      name: bucketconverter
      fieldPath: metadata.namespace
    targets:
      - select:
          kind: SecretStore
          name: bucketconverter
        fieldPaths:
          - spec.provider.kubernetes.remoteNamespace
