apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: convert-secret
  namespace: default
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - create
      - update
      - patch
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: convert-secret
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: convert-secret
subjects:
  - kind: ServiceAccount
    name: convert-secret
    namespace: default
